--- 
abstract: Stop Execution Of A Catalyst App
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  DirHandle: 0
  File::Spec: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Apoptosis
no_index: 
  directory: 
    - inc
    - t
recommends: 
  GTop: 0.15
version: 0.00002
